# Generated by Django 5.0.1 on 2025-05-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('specialite', models.CharField(max_length=50)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='cabinet.dossiermedical')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='cabinet.dossiermedical')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.medecin')),
            ],
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.patient'),
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('motif', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.rendezvous')),
            ],
        ),
    ]
