# Generated by Django 5.2 on 2025-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_facture_statut_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('PATIENT', 'patient'), ('MEDECIN', 'médecin')], max_length=128)),
            ],
        ),
    ]
