# Generated by Django 5.2 on 2025-05-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_authentification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authentification',
        ),
    ]
