# Generated by Django 5.2 on 2025-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_delete_authentification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
