# Generated by Django 5.2 on 2025-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_facture_date_emission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='rendez_vous',
        ),
        migrations.AddField(
            model_name='facture',
            name='Nomcomplet_med',
            field=models.CharField(choices=[('DR1', 'Dr.Ben Saad Nadia'), ('DR2', 'Dr.Moubaraki Houda'), ('DR3', 'Dr.Kabbaj Fouad'), ('DR4', 'Dr.Afifi Yasser'), ('DR5', 'Dr.Sakhi Othmane'), ('DR6', 'Dr.Belghiti Yousra')], default='Dr.Kabbaj Fouad', max_length=30),
        ),
        migrations.AddField(
            model_name='facture',
            name='Nompat',
            field=models.CharField(default='aucun', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='emailpat',
            field=models.EmailField(default='aucun', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='prenompat',
            field=models.CharField(default='aucun', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
