# Generated by Django 5.0.1 on 2025-05-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_remove_facture_rendez_vous_facture_nomcomplet_med_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='rendez_vous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='cabinet.rendezvous'),
        ),
    ]
