# Generated by Django 5.0.1 on 2025-05-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_facture_rendez_vous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='Nomcomplet_med',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='Nompat',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='emailpat',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='prenompat',
        ),
    ]
