# Generated by Django 5.0.1 on 2025-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_remove_facture_nomcomplet_med_remove_facture_nompat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents',
            field=models.TextField(default=''),
        ),
    ]
