# Generated by Django 5.0.1 on 2025-05-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_dossiermedical_antecedents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='antecedents',
        ),
    ]
